// ─────────────────────────────────────────────────────────────
//  ROAST LIBRARY
//  The generator combines a SETUP + PUNCHLINE (same topic) and,
//  sometimes, a CALLBACK — or fires a ONE-LINER. All editable in /admin.
//  kind: 'oneliner' | 'setup' | 'punchline' | 'callback'
//  topic: football | late | anime | study | gaming | gym | food | general
// ─────────────────────────────────────────────────────────────
const R = (kind, topic, text) => ({ kind, topic, text });

module.exports = [
  // ── ONE-LINERS ────────────────────────────────────────────
  R('oneliner', 'football', "Bro has never met a perfect pass he couldn't ignore."),
  R('oneliner', 'football', "His biggest enemy isn't the defender. It's the football itself."),
  R('oneliner', 'football', "Shiv's pass had a 99% completion chance. SIR found the 1%."),
  R('oneliner', 'football', "He's a midfielder in the same way a traffic cone is a defender."),
  R('oneliner', 'football', "The ball has a restraining order against his feet."),
  R('oneliner', 'football', "Nationals called. They said 'wrong number'."),
  R('oneliner', 'football', "He calls it 'letting the ball run'. The ball calls it 'freedom'."),
  R('oneliner', 'football', "His heat map is just a screenshot of the bench."),
  R('oneliner', 'football', "Alex, Jason, and Shiv have all passed to him. None of them will speak about it."),
  R('oneliner', 'football', "He doesn't miss passes. He specializes in them."),
  R('oneliner', 'football', "Bro doesn't miss opportunities. He collects them."),
  R('oneliner', 'late', "Bro says 'five minutes' like time is optional."),
  R('oneliner', 'late', "Even the loading screen has better timing."),
  R('oneliner', 'late', "He was late to his own birth. The doctors are still waiting."),
  R('oneliner', 'late', "His 'on my way' has a longer runtime than One Piece."),
  R('oneliner', 'late', "Google Maps gives up when he says 'I'm close'."),
  R('oneliner', 'late', "He's not late. Everyone else is just aggressively early."),
  R('oneliner', 'anime', "His anime watchlist has more commitment than his homework."),
  R('oneliner', 'anime', "At this point anime isn't a hobby. It's a full-time occupation with overtime."),
  R('oneliner', 'anime', "He has a training arc for everything except training."),
  R('oneliner', 'anime', "He's seen 400 episodes of people trying hard and absorbed none of it."),
  R('oneliner', 'anime', "'Just one more episode' — SIR, 4 hours ago."),
  R('oneliner', 'study', "His study timetable has been under construction since birth."),
  R('oneliner', 'study', "He opens the textbook the way other people open a horror movie: eyes closed."),
  R('oneliner', 'study', "Bro's revision strategy is a prayer and a pen."),
  R('oneliner', 'study', "The exam paper looked at him and also felt unprepared."),
  R('oneliner', 'study', "He doesn't study last minute. He studies during the minute."),
  R('oneliner', 'gaming', "In BGMI he lands hot and leaves cold."),
  R('oneliner', 'gaming', "His Free Fire Booyah exists only in his stories."),
  R('oneliner', 'gaming', "His aim is like his passing: technically in the same room."),
  R('oneliner', 'gaming', "He rage-quits games with more energy than he plays them."),
  R('oneliner', 'gaming', "His squad mutes him for 'tactical reasons'."),
  R('oneliner', 'gym', "He goes to the gym at 11 PM so nobody can witness the workout."),
  R('oneliner', 'gym', "His gym membership is the most consistent thing about his gym life."),
  R('oneliner', 'gym', "He does one set, takes one selfie, and calls it a session."),
  R('oneliner', 'gym', "The only thing he lifts consistently is his phone."),
  R('oneliner', 'food', "He has never missed a plate of biryani. Passing coaches are furious."),
  R('oneliner', 'food', "If Shiv passed him a biryani instead of a ball, he'd be at nationals."),
  R('oneliner', 'food', "He eats like the food owes him money."),
  R('oneliner', 'food', "His positioning near a buffet is genuinely world-class."),
  R('oneliner', 'food', "Bro's diet has more range than his passing."),
  R('oneliner', 'general', "He's lazy in a way that's honestly kind of athletic."),
  R('oneliner', 'general', "His exes' names gave him a title. His football gave him nothing."),
  R('oneliner', 'general', "SIR: Seriously Impressive Rest."),
  R('oneliner', 'general', "Bro has main-character energy with side-character output."),
  R('oneliner', 'general', "He survived another year. Mostly by accident."),

  // ── SETUPS ────────────────────────────────────────────────
  R('setup', 'football', "Shiv played a perfect pass today."),
  R('setup', 'football', "Alex threaded a ball through three defenders."),
  R('setup', 'football', "Jason crossed it onto a plate."),
  R('setup', 'football', "The coach asked him to control the ball."),
  R('setup', 'football', "The nationals selector came to watch him play."),
  R('setup', 'football', "They told him a midfielder has to be everywhere."),
  R('setup', 'late', "We said the match starts at 5."),
  R('setup', 'late', "He said 'coming in 5 minutes'."),
  R('setup', 'late', "We planned to meet at the ground at 4 PM sharp."),
  R('setup', 'anime', "He said he'd study after one episode."),
  R('setup', 'anime', "He watched a 200-episode training arc."),
  R('setup', 'anime', "He said anime taught him about never giving up."),
  R('setup', 'study', "Exam was at 9 AM."),
  R('setup', 'study', "He opened the book the night before the exam."),
  R('setup', 'study', "The teacher asked if he had any questions."),
  R('setup', 'gaming', "He landed at the hot drop in BGMI."),
  R('setup', 'gaming', "He said he was 'cracked' at Free Fire."),
  R('setup', 'gaming', "His squad gave him the sniper."),
  R('setup', 'gym', "He announced he's going to the gym every day."),
  R('setup', 'gym', "He walked into the gym at 11:30 PM."),
  R('setup', 'food', "Somebody said the biryani was ready."),
  R('setup', 'food', "There were 3 plates on the table."),
  R('setup', 'food', "The waiter asked if he wanted a second serving."),

  // ── PUNCHLINES ────────────────────────────────────────────
  R('punchline', 'football', "SIR received it in a different postcode."),
  R('punchline', 'football', "He wasn't even looking. He was checking his phone."),
  R('punchline', 'football', "The ball is still rolling. Scientists are tracking it."),
  R('punchline', 'football', "He controlled it straight out for a throw-in. Opposition throw-in."),
  R('punchline', 'football', "The selector left at half-time and changed careers."),
  R('punchline', 'football', "He interpreted 'everywhere' as 'somewhere near the water bottles'."),
  R('punchline', 'late', "He arrived when the match ended. Both halves."),
  R('punchline', 'late', "That was Tuesday. It is now Friday."),
  R('punchline', 'late', "He was still in bed, and the bed was winning."),
  R('punchline', 'anime', "That was 14 episodes ago. The book is still closed."),
  R('punchline', 'anime', "He absorbed zero training and all of the crying."),
  R('punchline', 'anime', "He gave up on the sentence halfway through."),
  R('punchline', 'study', "He started revising at 8:45. In the exam hall."),
  R('punchline', 'study', "The book started revising him."),
  R('punchline', 'study', "He asked what subject this was."),
  R('punchline', 'gaming', "He got knocked before his parachute opened."),
  R('punchline', 'gaming', "He got eliminated by a bot. The bot apologised."),
  R('punchline', 'gaming', "He scoped in and then closed the app 'by accident'."),
  R('punchline', 'gym', "'Every day' had a 24-hour cooldown that never reset."),
  R('punchline', 'gym', "The gym closed at 11:35. Great session."),
  R('punchline', 'food', "For the first time in his life, SIR did not miss."),
  R('punchline', 'food', "Two are gone. He's negotiating for the third."),
  R('punchline', 'food', "He said 'no' with his mouth and 'yes' with everything else."),

  // ── CALLBACKS ─────────────────────────────────────────────
  R('callback', 'general', "Unnational, as always."),
  R('callback', 'general', "This is why he's SIR."),
  R('callback', 'general', "Happy birthday though."),
  R('callback', 'general', "Case file updated."),
  R('callback', 'general', "The selectors have been notified."),
  R('callback', 'general', "Shiv is still waiting for that pass."),
  R('callback', 'general', "Five more minutes, he says."),
  R('callback', 'general', "The biryani, however, was finished."),
  R('callback', 'general', "Evidence logged."),
  R('callback', 'general', "We love him anyway. Barely."),
];
